#!/usr/bin/env python3
"""Gate B: does a pretrained EEG foundation model decode MI well enough to audit?

The uncertainty audit this project pivoted to only makes sense if the foundation
model is a serious decoder. If LaBraM sits near chance while a small supervised
convnet reaches 0.80, then "are its uncertainty estimates reliable under shift?"
is the wrong question -- the answer would be dominated by the model simply not
working, and the paper would become a transfer-failure claim instead.

This merges the foundation-model rows with the existing supervised rows, pairs
them by subject, and reports the gap with the same multiplicity discipline used
everywhere else in the project.

Usage::

    python src/scripts/make_gate_b_comparison.py
    python src/scripts/make_gate_b_comparison.py --fm-csv results/fm_probe/fm_probe_finetune_subject_metrics.csv
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd

SCRIPTS = Path(__file__).resolve().parent
if str(SCRIPTS) not in sys.path:
    sys.path.insert(0, str(SCRIPTS))

from make_multiplicity_table import (  # noqa: E402
    attainable_p_floor,
    benjamini_hochberg,
    holm,
    wilcoxon_p,
)

COMPARISON_CSV = Path("results") / "validation_only_selection_dataset_comparison.csv"
DEFAULT_FM_GLOB = "results/fm_probe/fm_probe_*_subject_metrics.csv"
REFERENCES = ("baseline", "seed_ensemble")
#: Prefixes identifying foundation-model rows across both runners.
FM_PREFIXES = ("labram", "cbramod", "eegpt", "biot")
#: Random-init rows are architecture-matched controls, not foundation models.
#: Counting them as FM rows would let a control win "best_fm" and corrupt the verdict.
CONTROL_MARKER = "randinit"
METRICS = ("accuracy", "Brier", "ECE", "NLL")
LOWER_IS_BETTER = {"Brier", "ECE", "NLL"}
EPS = 1e-12


def load_fm_rows(paths: list[Path]) -> pd.DataFrame:
    frames = []
    for path in paths:
        if not path.exists():
            continue
        frames.append(pd.read_csv(path))
    if not frames:
        raise SystemExit("no foundation-model result CSVs found; run run_fm_probe.py first")
    return pd.concat(frames, ignore_index=True)


def _escape(text: str) -> str:
    return str(text).replace("_", r"\_")


def write_latex(
    path: Path,
    summary: pd.DataFrame,
    tests: pd.DataFrame,
    controls: pd.DataFrame,
    dataset: str,
) -> None:
    """Emit the paper's main table: every method, ranked, with its role marked."""
    lines = [
        r"% Generated by src/scripts/make_gate_b_comparison.py -- do not edit by hand.",
        r"\begin{table}[t]",
        r"\centering",
        r"\small",
        r"\begin{tabular}{llrrrr}",
        r"\toprule",
        r"Method & Role & $n$ & Acc. & Brier & ECE \\",
        r"\midrule",
    ]
    for _, row in summary.iterrows():
        if row.get("is_random_init_control"):
            role = "random-init control"
        elif row.get("is_foundation_model"):
            role = "foundation model"
        else:
            role = "supervised"
        ece = row.get("heldout_ECE", float("nan"))
        lines.append(
            f"{_escape(row['method'])} & {role} & {int(row['n_subjects'])} & "
            f"{row['heldout_accuracy']:.3f} & {row['heldout_Brier']:.3f} & "
            + (f"{ece:.3f}" if pd.notna(ece) else "--")
            + r" \\"
        )
    chance_acc = float(summary["chance_accuracy"].iloc[0])
    chance_brier = float(summary["chance_Brier"].iloc[0])
    lines += [
        r"\midrule",
        rf"\emph{{chance}} & --- & --- & \emph{{{chance_acc:.3f}}} & "
        rf"\emph{{{chance_brier:.3f}}} & --- \\",
        r"\bottomrule",
        r"\end{tabular}",
    ]

    n_sig = int((tests["p_bh"] < 0.05).sum()) if not tests.empty else 0
    caption = (
        rf"Held-out performance on {_escape(dataset)}, averaged over subjects. "
        rf"Every configuration is selected on the validation subset only. "
        rf"Of {len(tests)} paired foundation-model vs.\ supervised tests, "
        rf"{n_sig} survive Benjamini--Hochberg correction at $\alpha=0.05$."
    )
    if not controls.empty:
        acc = controls[controls["metric"] == "accuracy"]
        if not acc.empty:
            wins = int(acc["pretrained_wins"].sum())
            total = int(acc["n_subjects"].sum())
            caption += (
                rf" Pretrained weights beat an architecture-matched random "
                rf"initialisation on {wins} of {total} paired subject comparisons."
            )
    lines += [
        rf"\caption{{{caption}}}",
        r"\label{tab:gate-b}",
        r"\end{table}",
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--fm-csv", type=Path, nargs="*", default=None)
    ap.add_argument("--comparison-csv", type=Path, default=COMPARISON_CSV)
    ap.add_argument("--dataset", default="bci4_2a")
    ap.add_argument("--out-dir", type=Path, default=Path("results") / "paper_calibration_stats" / "gate_b")
    ap.add_argument("--alpha", type=float, default=0.05)
    args = ap.parse_args()

    fm_paths = list(args.fm_csv) if args.fm_csv else sorted(Path().glob(DEFAULT_FM_GLOB))
    fm = load_fm_rows(fm_paths)
    # The supervised CSV spells MOABB datasets "BNCI2014_004" while the
    # foundation-model runners use the lowercase file slug. Matching case
    # sensitively would silently yield no rows for every MOABB dataset.
    want = str(args.dataset).lower()
    fm = fm[fm["dataset"].astype(str).str.lower() == want]
    if fm.empty:
        raise SystemExit(f"no foundation-model rows for dataset {args.dataset}")

    supervised = pd.read_csv(args.comparison_csv)
    supervised = supervised[
        (supervised["dataset"].astype(str).str.lower() == want)
        & supervised["experiment_key"].isin(REFERENCES)
    ]
    if supervised.empty:
        raise SystemExit(f"no reference rows ({REFERENCES}) for {args.dataset}")

    # The comparison CSV's subject column is object-typed because other datasets
    # use string ids ("k3b"), so bci4_2a subjects arrive as "1" while the
    # foundation-model CSV has int 1. Pairing on mismatched types silently yields
    # an empty intersection and no tests at all.
    fm = fm.assign(subject=fm["subject"].astype(str))
    supervised = supervised.assign(subject=supervised["subject"].astype(str))

    unsafe = pd.concat(
        [
            fm[fm["eval_labels_used_for_selection"].astype(str).str.lower() == "true"],
            supervised[supervised["eval_labels_used_for_selection"].astype(str).str.lower() == "true"],
        ]
    )
    if not unsafe.empty:
        raise SystemExit(f"refusing to report: {len(unsafe)} rows used eval labels for selection")

    args.out_dir.mkdir(parents=True, exist_ok=True)

    # --- per-method held-out summary ---
    rows = []
    for key, part in pd.concat([fm, supervised], ignore_index=True).groupby("experiment_key"):
        record = {"method": key, "n_subjects": int(part["subject"].nunique())}
        for metric in METRICS:
            col = f"heldout_{metric}"
            if col in part:
                values = pd.to_numeric(part[col], errors="coerce").dropna()
                record[f"heldout_{metric}"] = float(values.mean()) if len(values) else np.nan
        record["chance_accuracy"] = float(part["chance_accuracy"].iloc[0])
        record["chance_Brier"] = float(part["chance_Brier"].iloc[0])
        is_fm = str(key).startswith(FM_PREFIXES)
        record["is_random_init_control"] = is_fm and CONTROL_MARKER in str(key)
        record["is_foundation_model"] = is_fm and not record["is_random_init_control"]
        # The reference arms come from a different training loop -- multi-scale
        # crops with aggregation, not single windows. They belong here, because
        # they are the strongest supervised result and so the honest bar for
        # "can a foundation model beat supervised training". They are labelled
        # because a difference against them mixes training recipe with
        # architecture, which is exactly the confound that invalidated the
        # section 8h band term.
        record["training_recipe"] = (
            "" if is_fm else "cropped+aggregated" if str(key) in REFERENCES else "single-window"
        )
        rows.append(record)
    summary = pd.DataFrame(rows).sort_values("heldout_accuracy", ascending=False)
    summary.to_csv(args.out_dir / "gate_b_summary.csv", index=False)

    # --- paired FM vs reference ---
    tests = []
    for fm_key, fm_part in fm.groupby("experiment_key"):
        fm_by_subject = fm_part.set_index("subject")
        for ref_key, ref_part in supervised.groupby("experiment_key"):
            ref_by_subject = ref_part.set_index("subject")
            shared = sorted(set(fm_by_subject.index) & set(ref_by_subject.index))
            if not shared:
                continue
            for metric in METRICS:
                col = f"heldout_{metric}"
                if col not in fm_part or col not in ref_part:
                    continue
                a = pd.to_numeric(ref_by_subject.loc[shared, col], errors="coerce")
                b = pd.to_numeric(fm_by_subject.loc[shared, col], errors="coerce")
                delta = (b - a).dropna().to_numpy(dtype=float)
                if delta.size == 0:
                    continue
                lower = metric in LOWER_IS_BETTER
                wins = int((delta < -EPS).sum()) if lower else int((delta > EPS).sum())
                losses = int((delta > EPS).sum()) if lower else int((delta < -EPS).sum())
                nonzero = int(np.count_nonzero(~np.isclose(delta, 0.0)))
                tests.append(
                    {
                        "fm_method": fm_key,
                        "reference": ref_key,
                        "metric": metric,
                        "n_subjects": int(delta.size),
                        "fm_mean": float(b.mean()),
                        "reference_mean": float(a.mean()),
                        "mean_delta": float(delta.mean()),
                        "fm_wins": wins,
                        "fm_losses": losses,
                        "p_raw": wilcoxon_p(delta),
                        "attainable_p_floor": attainable_p_floor(nonzero),
                    }
                )
    tests_df = pd.DataFrame(tests)
    if tests_df.empty:
        raise SystemExit(
            "no paired rows between foundation-model and reference results; "
            "check that subject identifiers match across the two files"
        )
    if not tests_df.empty:
        ps = tests_df["p_raw"].tolist()
        tests_df["n_tests"] = len(ps)
        tests_df["p_holm"], _ = holm(ps, args.alpha)
        tests_df["p_bh"], _ = benjamini_hochberg(ps, args.alpha)
        tests_df = tests_df.sort_values(["metric", "p_raw"])
        tests_df.to_csv(args.out_dir / "gate_b_paired_tests.csv", index=False)

    # --- pretrained vs architecture-matched random init ---
    # The comparison that decides whether pretraining contributes anything at
    # all. Paired within subject, so it is not confounded by subject difficulty.
    control_rows = []
    fm_keys = set(fm["experiment_key"].unique())
    for key in sorted(k for k in fm_keys if CONTROL_MARKER not in str(k)):
        # A control carries the pretrained row's key with the marker inserted;
        # match by stripping the marker back off each candidate.
        matches = [
            k
            for k in fm_keys
            if CONTROL_MARKER in str(k) and str(k).replace(f"_{CONTROL_MARKER}", "") == str(key)
        ]
        if not matches:
            continue
        control_key = matches[0]
        pre = fm[fm["experiment_key"] == key].set_index("subject")
        ctl = fm[fm["experiment_key"] == control_key].set_index("subject")
        shared = sorted(set(pre.index) & set(ctl.index))
        if not shared:
            continue
        for metric in METRICS:
            col = f"heldout_{metric}"
            a = pd.to_numeric(ctl.loc[shared, col], errors="coerce")
            b = pd.to_numeric(pre.loc[shared, col], errors="coerce")
            delta = (b - a).dropna().to_numpy(dtype=float)
            if delta.size == 0:
                continue
            lower = metric in LOWER_IS_BETTER
            nonzero = int(np.count_nonzero(~np.isclose(delta, 0.0)))
            control_rows.append(
                {
                    "pretrained": key,
                    "control": control_key,
                    "metric": metric,
                    "n_subjects": int(delta.size),
                    "pretrained_mean": float(b.mean()),
                    "random_init_mean": float(a.mean()),
                    "mean_delta": float(delta.mean()),
                    "pretrained_wins": int((delta < -EPS).sum()) if lower else int((delta > EPS).sum()),
                    "pretrained_losses": int((delta > EPS).sum()) if lower else int((delta < -EPS).sum()),
                    "p_raw": wilcoxon_p(delta),
                    "attainable_p_floor": attainable_p_floor(nonzero),
                }
            )
    control_df = pd.DataFrame(control_rows)
    if not control_df.empty:
        ps = control_df["p_raw"].tolist()
        control_df["n_tests"] = len(ps)
        control_df["p_holm"], _ = holm(ps, args.alpha)
        control_df["p_bh"], _ = benjamini_hochberg(ps, args.alpha)
        control_df = control_df.sort_values(["metric", "p_raw"])
        control_df.to_csv(args.out_dir / "gate_b_pretrained_vs_random.csv", index=False)

    # --- verdict ---
    fm_summary = summary[summary["is_foundation_model"]]
    best_fm = fm_summary.loc[fm_summary["heldout_accuracy"].idxmax()] if not fm_summary.empty else None
    ref_summary = summary[
        ~summary["is_foundation_model"] & ~summary["is_random_init_control"]
    ]
    best_ref = ref_summary.loc[ref_summary["heldout_accuracy"].idxmax()] if not ref_summary.empty else None

    verdict: dict = {"dataset": args.dataset, "alpha": args.alpha}
    if best_fm is not None and best_ref is not None:
        chance = float(best_fm["chance_accuracy"])
        fm_lift = float(best_fm["heldout_accuracy"]) - chance
        ref_lift = float(best_ref["heldout_accuracy"]) - chance
        ratio = fm_lift / ref_lift if ref_lift > 0 else float("nan")
        verdict.update(
            {
                "best_fm": str(best_fm["method"]),
                "best_fm_accuracy": float(best_fm["heldout_accuracy"]),
                "best_reference": str(best_ref["method"]),
                "best_reference_accuracy": float(best_ref["heldout_accuracy"]),
                "chance_accuracy": chance,
                "fm_lift_over_chance": fm_lift,
                "reference_lift_over_chance": ref_lift,
                "fm_fraction_of_reference_lift": ratio,
            }
        )
        # A model recovering less than half the supervised lift is not a credible
        # subject of a calibration audit; the audit would measure its failure.
        if ratio >= 0.75:
            verdict["recommendation"] = "PROCEED: FM is a credible decoder; audit its uncertainty"
        elif ratio >= 0.5:
            verdict["recommendation"] = "MARGINAL: usable but weak; consider reframing"
        else:
            verdict["recommendation"] = (
                "REFRAME: FM recovers <50% of supervised lift; an uncertainty audit would "
                "measure transfer failure, not calibration"
            )
    (args.out_dir / "gate_b_verdict.json").write_text(json.dumps(verdict, indent=2), encoding="utf-8")

    write_latex(args.out_dir / "gate_b_table.tex", summary, tests_df, control_df, args.dataset)

    print("=== held-out summary ===")
    cols = ["method", "n_subjects", "heldout_accuracy", "heldout_Brier", "is_foundation_model"]
    print(summary[cols].round(4).to_string(index=False))
    if not tests_df.empty:
        print("\n=== paired vs references (accuracy) ===")
        acc = tests_df[tests_df["metric"] == "accuracy"]
        show = ["fm_method", "reference", "n_subjects", "fm_mean", "reference_mean", "mean_delta", "p_raw", "p_bh"]
        print(acc[show].round(4).to_string(index=False))
    if not control_df.empty:
        print("\n=== pretrained vs random init (accuracy) ===")
        acc = control_df[control_df["metric"] == "accuracy"]
        show = [
            "pretrained", "n_subjects", "pretrained_mean", "random_init_mean",
            "mean_delta", "pretrained_wins", "pretrained_losses", "p_raw", "p_bh",
        ]
        print(acc[show].round(4).to_string(index=False))
    print("\n=== verdict ===")
    for key, value in verdict.items():
        print(f"  {key}: {value}")
    print(f"\nWrote {args.out_dir}")


if __name__ == "__main__":
    main()
